// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmRwuTaw_Hz2d4JSPVBhBOaNKE0pT-c4',
    appId: '1:258091654623:web:71d11e4e045fb278b8f86a',
    messagingSenderId: '258091654623',
    projectId: 'social-sphere-74efc',
    authDomain: 'social-sphere-74efc.firebaseapp.com',
    storageBucket: 'social-sphere-74efc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXyadTGTpxhll6_6tAhIiT2BVSG-Z1VsA',
    appId: '1:258091654623:android:c1a844c5e5aadafcb8f86a',
    messagingSenderId: '258091654623',
    projectId: 'social-sphere-74efc',
    storageBucket: 'social-sphere-74efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhyNbikQRilBsobgRGehvutjeyFkAPOg0',
    appId: '1:258091654623:ios:1a5204ad6eb26bdfb8f86a',
    messagingSenderId: '258091654623',
    projectId: 'social-sphere-74efc',
    storageBucket: 'social-sphere-74efc.appspot.com',
    iosBundleId: 'com.example.socialSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhyNbikQRilBsobgRGehvutjeyFkAPOg0',
    appId: '1:258091654623:ios:1a5204ad6eb26bdfb8f86a',
    messagingSenderId: '258091654623',
    projectId: 'social-sphere-74efc',
    storageBucket: 'social-sphere-74efc.appspot.com',
    iosBundleId: 'com.example.socialSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpmRwuTaw_Hz2d4JSPVBhBOaNKE0pT-c4',
    appId: '1:258091654623:web:3a756864bbdbcae1b8f86a',
    messagingSenderId: '258091654623',
    projectId: 'social-sphere-74efc',
    authDomain: 'social-sphere-74efc.firebaseapp.com',
    storageBucket: 'social-sphere-74efc.appspot.com',
  );
}
